bells_pro/bells/urls.py
from django.urls import path
from . import views

app_name = 'bells'


urlpatterns = [
    path('', views.defs.index, name='index'),
    path('login/', views.user_login.UserLoginView.as_view(), name='login'),
    path('dashboard/<str:user>', views.dashboard.DashBoardView.as_view(), name='dashboard'),
    path('article_create/<str:user>', views.article_create.ArticleCreateView.as_view(), name='article_create'),
    path('articles/<str:user>', views.article_list.ArticleListView.as_view(), name='articles'),
    path('article/<str:username>/<int:pk>', views.article.ArticleView.as_view(), name='article'),
    path('signup/', views.signup.SignUpView.as_view(), name='signup'),
    path('likes/<int:user_id>/<int:article_id>', views.defs.likes, name='likes'),
    path('trainers/<str:user>', views.trainer_list.TrainersView.as_view(), name='trainers'),
    path('follow/<int:user_id>/<int:trainer_id>', views.defs.follow, name='follow'),
    path('trainer_detail/<str:slug>', views.trainer.TrainerView.as_view(), name='trainer_detail'),
]

bells_pro/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bells/', include('bells.urls')),
    path('bells/', include('django.contrib.auth.urls')),
    path('mdeditor/', include('mdeditor.urls'))
]


# markeditor用
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bells_pro/bells/models.py
from django.db import models
from mdeditor.fields import MDTextField

from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, Group, Permission, GroupManager, PermissionManager, ContentType
from django.utils import timezone
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _

from mediumeditor.widgets import MediumEditorTextarea
#　原本
class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.
    Username and password are required. Other fields are optional.
    """
    email = models.EmailField('email', unique=True)

    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        'username',
        max_length=150,
        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
        validators=[username_validator],
        error_messages={
            'unique': "A user with that username already exists.",
        },
    )
    is_staff = models.BooleanField(
        'staff status',
        default=False,
        help_text='Designates whether the user can log into this admin site.',
    )
    is_active = models.BooleanField(
        'is_active',
        default=True,
        help_text=
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ,
    )

    is_trainer=models.BooleanField(
        'is_trainer',
        default=False,
        help_text=
            'can write article',
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    follows = models.ManyToManyField(
        'self',
        symmetrical=False,
        related_name="followers",
        blank=True,
    )



    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)


    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


    def __str__(self):
        return self.username

    def natural_key(self):
        return (self.username,)

class Article(models.Model):
    title = models.CharField(max_length=70)
    detail = MDTextField()
    # detail = models.TextField()
    # detail = MediumEditorTextarea()
    trainer = models.ForeignKey(User, on_delete=models.CASCADE)

    user_likes = models.ManyToManyField(
        User,
        related_name="likes",
        blank=True,
    )

    user_favorites = models.ManyToManyField(
        User,
        related_name="favorites",
        blank=True,
    )
    def __str__(self):
        return self.title

class Comment(models.Model):
    comment = models.CharField(max_length=256)
    article = models.ForeignKey(
        Article, 
        related_name="comments",
        on_delete=models.CASCADE,
        )
    user = models.ForeignKey(
        User, 
        related_name="commets",
        on_delete=models.SET_NULL, 
        null = True
        )

class Tag(models.Model):
    tag = models.CharField(max_length=20)
    article = models.ManyToManyField(
        Article,
        related_name="tags",
        blank=True,
    )

class QuestionBox(models.Model):
    detail = models.TextField()
    user = models.ForeignKey(
        User,
        related_name="question_box",
        on_delete=models.CASCADE
    )

class Answer(models.Model):
    question_box = models.ForeignKey(
        QuestionBox,
        related_name = "answers",
        on_delete=models.CASCADE
    )
    User = models.ForeignKey(
        User,
        related_name="answers",
        on_delete=models.SET_NULL,
        null=True
    )

bells_pro/bells/views.py
# from django.urls import reverse_lazy
# from django.contrib.auth.decorators import login_required

# from django.http import HttpResponse
# from django.shortcuts import redirect
# from django.shortcuts import render
# from django.urls import reverse

# from django.views import generic
# from .form import UserCreateForm, UserLoginForm, ArticleForm, MyForm
# from django.contrib.auth import (
#      get_user_model, logout as auth_logout,
# )
# from django.contrib.auth.views import LoginView
# from .models.article import Article

# from django.contrib.auth.mixins import LoginRequiredMixin
# import datetime


# User = get_user_model()

# def index(request):
#     return render(request, 'bells/index.html')
 

# def likes(request, user_id, article_id):
#     """いいねボタンをクリック"""
#     if request.method == 'POST':
#         user = User.objects.get(id = user_id)
#         print(user.username)
#         article = Article.objects.get(id = article_id)
#         like_check = User.objects.filter(likes=article).filter(id=user_id)
#         if like_check.count() == 0:
#             user.likes.add(article)
#             user.save()
#         else:
#             user.likes.remove(article)
#             user.save()
        
#         context = {
#             'like_number': like_check.count()
#         }

#         # necessary return?
#         return HttpResponse("ajax is done!")


# class SignUpView(generic.CreateView):
#     form_class = UserCreateForm
#     success_url = reverse_lazy('login')
#     template_name = 'registration/signup.html'


# class ArticleCreateView(generic.CreateView, LoginRequiredMixin):
#     # markdown
#     form_class = ArticleForm
#     # MediumEditorの場合
#     # form_class = MyForm
#     template_name = 'dashboard/article_create.html'

#     def post(self, request, *args, **kwargs):
#         form = self.form_class(request.POST)
#         if form.is_valid():
#             obj = form.save(commit=False)
#             obj.trainer = self.request.user
#             obj.save()
            
#             return redirect('bells:articles', user=self.request.user)


# class UserLoginView(LoginView):
#     form_class = UserLoginForm
#     template_name = 'registration/login.html'

#     swappable = 'AUTH_USER_MODEL'

# class DashBoardView(generic.TemplateView, LoginRequiredMixin):
#     template_name='dashboard/dashboard.html'

#     def get_context_data(self, **kwargs):
#         today = datetime.datetime.now()
#         last_week = today - datetime.timedelta(weeks=2)
        
#         articles = Article.objects.all().order_by('created_at').reverse()[0:3]
#         pickups = Article.objects.filter(created_at__gt=last_week, created_at__lt=today).order_by('user_likes').reverse()[0:3]
#         context = super().get_context_data(**kwargs)
#         context['articles'] = articles
#         context['pickups'] = pickups

#         context['user'] = self.request.user
#         context['username'] = self.request.user.username
#         context['likes_count'] =  self.request.user.likes.count()

#         return context



# class ArticlesView(generic.TemplateView, LoginRequiredMixin):
#     articles = Article.objects.all()
#     template_name='dashboard/articles.html'
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['articles'] = Article.objects.all().order_by('created_at').reverse()
#         return context

# class ArticleView(generic.DetailView, LoginRequiredMixin):
#     model = Article
#     template_name = 'dashboard/article_detail.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         login_user = self.request.user
#         print(login_user.id)
#         context['articles'] = Article.objects.get(id=self.kwargs['pk'])
#         context['likes_number'] =  context['articles'].user_likes.count()

#         like_check = User.objects.filter(likes=context['articles']).filter(id=login_user.id).count()
#         context['like_check'] = False if like_check == 0 else True
#         context['login_user'] = login_user


#         return context

bells_pro/bells/views/article.py
from django.views import generic
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin

from ..models.article import Article

User = get_user_model()

class ArticleView(generic.DetailView, LoginRequiredMixin):
    model = Article
    template_name = 'dashboard/article_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        login_user = self.request.user
        context['articles'] = Article.objects.get(id=self.kwargs['pk'])
        context['likes_number'] =  context['articles'].user_likes.count()

        like_check = User.objects.filter(likes=context['articles']).filter(id=login_user.id).count()
        context['like_check'] = False if like_check == 0 else True
        context['login_user'] = login_user


        return context

bells_pro/bells/views/article_create.py
from django.views import generic
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin

from ..form import ArticleForm, MyForm


class ArticleCreateView(generic.CreateView, LoginRequiredMixin):
    # markdown
    form_class = ArticleForm
    # MediumEditorの場合
    # form_class = MyForm
    template_name = 'dashboard/article_create.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.trainer = self.request.user
            obj.save()
            
            return redirect('bells:articles', user=self.request.user)

bells_pro/bells/views/article_list.py
from django.views import generic
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from ..models.article import Article


class ArticleListView(generic.TemplateView, LoginRequiredMixin):
    articles = Article.objects.all()
    template_name='dashboard/articles.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles'] = Article.objects.all().order_by('created_at').reverse()
        return context

bells_pro/bells/views/dashboard.py
from django.views import generic
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from ..models.article import Article
import datetime

class DashBoardView(generic.TemplateView, LoginRequiredMixin):
    template_name='dashboard/dashboard.html'

    def get_context_data(self, **kwargs):
        today = datetime.datetime.now()
        last_week = today - datetime.timedelta(weeks=2)
        
        articles = Article.objects.all().order_by('created_at').reverse()[0:3]
        pickups = Article.objects.filter(created_at__gt=last_week, created_at__lt=today).order_by('user_likes').reverse()[0:3]
        context = super().get_context_data(**kwargs)
        context['articles'] = articles
        context['pickups'] = pickups

        context['user'] = self.request.user
        context['username'] = self.request.user.username
        context['likes_count'] =  self.request.user.likes.count()

        return context

bells_pro/bells/views/defs.py
from django.http import HttpResponse
from django.shortcuts import render
from ..models import User

def index(request):
    return render(request, 'bells/index.html')
 

def likes(request, user_id, article_id):
    """いいねボタンをクリック"""
    if request.method == 'POST':
        user = User.objects.get(id = user_id)
        article = Article.objects.get(id = article_id)
        like_check = User.objects.filter(likes=article).filter(id=user_id)
        if like_check.count() == 0:
            user.likes.add(article)
            user.save()
        else:
            user.likes.remove(article)
            user.save()
        
        context = {
            'like_number': like_check.count()
        }

        # necessary return?
        return HttpResponse("ajax is done!")

def follow(request, user_id, trainer_id):
    # followボタンをクリック
    if request.method == 'POST':
        user = User.objects.get(id = user_id)
        trainer = User.objects.get(id=trainer_id)
        # トレーナーのフォロワーの中に自分がいるかをチェック
        follow_check = trainer.followers.filter(id=user_id)

        if follow_check.count() == 0:
            user.follows.add(trainer)
            user.save()
        else:
            user.follows.remove(trainer)
            user.save()
        
        context = {
            'follow_number' : follow_check.count()
        }

        return HttpResponse("ajax is done!")    

bells_pro/bells/views/signup.py
from django.views import generic
from django.urls import reverse_lazy
from ..form import UserCreateForm



class SignUpView(generic.CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

bells_pro/bells/views/trainer.py
from django.views import generic
from django.urls import reverse

from ..models.user import User

class TrainerView(generic.DetailView):
    model = User
    template_name = "dashboard/trainer_detail.html"
    slug_field = 'username'

    def get_context_data(self, **kwargs):
        print(self.kwargs['slug'])

        context = super().get_context_data(**kwargs)
        context['trainer'] = User.objects.get(username=self.kwargs['slug'])
        # context['follower'] = context['trainer'][0].followers.count()
        # context['articles'] = context['follower'].trainer_set

        return context

bells_pro/bells/views/trainer_list.py
from django.views import generic
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from ..models.user import User


class TrainersView(generic.TemplateView, LoginRequiredMixin):
    template_name='dashboard/trainers.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trainers'] = User.objects.all().filter(is_trainer=True)
        context['user'] = self.request.user

        return context

bells_pro/bells/views/user_login.py
from django.contrib.auth.views import LoginView
from ..form import UserLoginForm

class UserLoginView(LoginView):
    form_class = UserLoginForm
    template_name = 'registration/login.html'

    swappable = 'AUTH_USER_MODEL'

bells_pro/bells/templates/base_centered.html
{% extends "base.html" %}

{% block body %}
    
    <div class="row text-center">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">

                    {% block content %}{% endblock %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}

bells_pro/bells/templates/base_dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta name="csrf-token" content="{{ csrf_token }}" /> 

        <link rel="apple-touch-icon" sizes="76x76" href="{% static 'dashboard/assets/img/apple-icon.png'% }">
        <link rel="icon" type="image/png" href="{% static 'dashboard/assets/img/favicon.png' %}">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title>
          Paper Dashboard 2 by Creative Tim
        </title>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
        <!--     Fonts and icons     -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
        <!-- CSS Files -->
        <link href="{% static 'dashboard/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
        <link href="{% static 'dashboard/assets/css/paper-dashboard.css' %}" rel="stylesheet" />

        <!-- 手作りcss -->
        <link href="{% static 'dashboard/assets/css/original.css' %}" rel="stylesheet" />

        <!-- 手作りscss -->
        <script src="{% static 'dashboard/assets/js/original.js' %}"></script>
      </head>
      
      <body>
      <div class="center_container">
        <div class="sidebar" data-color="white" data-active-color="danger">
            <div class="sidebar-wrapper">
                <div class="col-md-11 ml-md-auto mr-md-auto">
                    <div class="card card-user">
                      <div class="image">
                        <img src="{% static 'dashboard/assets/img/damir-bosnjak.jpg' %}" alt="...">
                      </div>
                      <div class="card-body">
                        <div class="author">
                          <a href="#">
                            <img class="avatar border-gray" src="{% static 'dashboard/assets/img/bodybuilder.png' %}" alt="...">
                            <h5 class="title">{{ user.username }}</h5>
                          </a>
                          <p class="description">
                            @chetfaker
                          </p>
                        </div>
                        <p class="description text-center">testestest</p>
                      </div>
                      <div class="card-footer">
                        <hr>
                        <div class="button-container">
                          <div class="row">
                            <div class="col-lg-3 col-md-6 col-6 ml-auto">
                              <h5>{{ likes_count }}<br><small> likes</small></h5>
                            </div>
                            <div class="col-lg-4 col-md-6 col-6 ml-auto mr-auto">
                              <h5>{{user.aa}}<br><small>favorites</small></h5>
                            </div>
                            <div class="col-lg-3 mr-auto">
                              <h5>24,6$<br><small>Spent</small></h5>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>
                    <div class="card">
                      <div class="card-header">
                        <h4 class="card-title">Team Members</h4>
                      </div>
                      <div class="card-body">
                        <ul class="list-unstyled team-members">
                          <li>
                            <div class="row">
                              <div class="col-md-2 col-2">
                                <div class="avatar">
                                  <img src="../assets/img/faces/ayo-ogunseinde-2.jpg" alt="Circle Image" class="img-circle img-no-padding img-responsive">
                                </div>
                              </div>
                              <div class="col-md-7 col-7">
                                DJ Khaled
                                <br />
                                <span class="text-muted"><small>Offline</small></span>
                              </div>
                              <div class="col-md-3 col-3 text-right">
                                <btn class="btn btn-sm btn-outline-success btn-round btn-icon"><i class="fa fa-envelope"></i></btn>
                              </div>
                            </div>
                          </li>
                          <li>
                            <div class="row">
                              <div class="col-md-2 col-2">
                                <div class="avatar">
                                  <img src="../assets/img/faces/joe-gardner-2.jpg" alt="Circle Image" class="img-circle img-no-padding img-responsive">
                                </div>
                              </div>
                              <div class="col-md-7 col-7">
                                Creative Tim
                                <br />
                                <span class="text-success"><small>Available</small></span>
                              </div>
                              <div class="col-md-3 col-3 text-right">
                                <btn class="btn btn-sm btn-outline-success btn-round btn-icon"><i class="fa fa-envelope"></i></btn>
                              </div>
                            </div>
                          </li>
                          <li>
                            <div class="row">
                              <div class="col-md-2 col-2">
                                <div class="avatar">
                                  <img src="../assets/img/faces/clem-onojeghuo-2.jpg" alt="Circle Image" class="img-circle img-no-padding img-responsive">
                                </div>
                              </div>
                              <div class="col-ms-7 col-7">
                                Flume
                                <br />
                                <span class="text-danger"><small>Busy</small></span>
                              </div>
                              <div class="col-md-3 col-3 text-right">
                                <btn class="btn btn-sm btn-outline-success btn-round btn-icon"><i class="fa fa-envelope"></i></btn>
                              </div>
                            </div>
                          </li>
                        </ul>
                      </div>
                    </div>
                




              <ul class="nav">
                <li class="active ">
                  <a href="{% url 'bells:dashboard' user %}">
                    <i class="nc-icon nc-bank"></i>
                    <p>ダッシュボード</p>
                  </a>
                </li>
                <li>
                  <a href="{% url 'bells:articles' user %}">
                    <i class="nc-icon nc-diamond"></i>
                    <p>最新記事</p>
                  </a>
                </li>
                <li>
                  <a href="{% url 'bells:trainers' user %}">
                    <i class="nc-icon nc-pin-3"></i>
                    <p>トレーナーリスト</p>
                  </a>
                </li>
                <li>
                  {% if user.is_trainer %}
                  <a href="{% url 'bells:article_create' user %}">
                    <i class="nc-icon nc-bell-55"></i>
                    <p>記事作成</p>
                  </a>
                  {% endif %}
                </li>
                <li>
                  <a href="./user.html">
                    <i class="nc-icon nc-single-02"></i>
                    <p>User Profile</p>
                  </a>
                </li>
                <li>
                  <a href="./tables.html">
                    <i class="nc-icon nc-tile-56"></i>
                    <p>Table List</p>
                  </a>
                </li>
                <li>
                  <a href="./typography.html">
                    <i class="nc-icon nc-caps-small"></i>
                    <p>Typography</p>
                  </a>
                </li>
                <li class="active-pro">
                  <a href="./upgrade.html">
                    <i class="nc-icon nc-spaceship"></i>
                    <p>Upgrade to PRO</p>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="main-panel">
            <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
              <div class="container-fluid">
                <div class="navbar-wrapper">
                    <!-- スマホ時ナビボタン右側 -->
                  <div class="navbar-toggle">
                    <button type="button" class="navbar-toggler">
                      <span class="navbar-toggler-bar bar1"></span>
                      <span class="navbar-toggler-bar bar2"></span>
                      <span class="navbar-toggler-bar bar3"></span>
                    </button>
                  </div>
                  <a class="navbar-brand" href="javascript:;">Paper Dashboard 2</a>
                </div>
                
                <!-- スマホ時のナビボタン左側 -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-bar navbar-kebab"></span>
                  <span class="navbar-toggler-bar navbar-kebab"></span>
                  <span class="navbar-toggler-bar navbar-kebab"></span>
                </button>
                <!-- justify-content-endで左の寄せてる -->
                <div class="collapse navbar-collapse justify-content-end" id="navigation">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link btn-magnify" href="javascript:;">
                        <i class="nc-icon nc-layout-11"></i>
                        <p>
                          <span class="d-lg-none d-md-block">Stats</span>
                        </p>
                      </a>
                    </li>
                    <li class="nav-item btn-rotate dropdown">
                      <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="nc-icon nc-bell-55"></i>
                        <p>
                          <span class="d-lg-none d-md-block">Some Actions</span>
                        </p>
                      </a>
                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                      </div>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link btn-rotate" href="javascript:;">
                        <i class="nc-icon nc-settings-gear-65"></i>
                        <p>
                          <span class="d-lg-none d-md-block">Account</span>
                        </p>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>
            {% block dashboard %}{% endblock %}
        </div>
      </div>
        <!--   Core JS Files   -->
        <script src="{% static 'dashboard/assets/js/core/jquery.min.js' %}"></script>
        <script src="{% static 'dashboard/assets/js/core/popper.min.js' %}"></script>
        <script src="{% static 'dashboard/assets/js/core/bootstrap.min.js' %}"></script>
        <script src="{% static 'dashboard/assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
        <!-- 手作りjs -->
        <script src="{% static 'dashboard/assets/js/original.js' %}"></script>
   
        <!--  Google Maps Plugin    -->
        <!-- <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script> -->
        <!-- Chart JS -->
        <script src="{% static 'dashboard/assets/js/plugins/chartjs.min.js' %}./assets/"></script>
        <!--  Notifications Plugin    -->
        <script src="{% static 'dashboard/assets/js/plugins/bootstrap-notify.js' %}"></script>
        <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
        <script src="{% static 'dashboard/assets/js/paper-dashboard.min.js' %}" type="text/javascript"></script>
        <!-- likes -->
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js"></script>    
        <script>
          $(document).ready(function() {
            // Javascript method's body can be found in assets/assets-for-demo/js/demo.js
            demo.initChartsPages();
          });
        </script>
      
      </body>
</html>

bells_pro/bells/templates/base_main.html
{% extends "base.html" %}

{% block body %}
    
    <div class="row text-center">
        {% block content %}{% endblock %}

    </div>

{% endblock %}