bells_pro/bells/urls.py
from django.urls import path
from . import views

app_name = 'bells'


urlpatterns = [
    path('', views.defs.index, name='index'),
    path('login/', views.user_login.UserLoginView.as_view(), name='login'),
    path('dashboard/<str:user>', views.dashboard.DashBoardView.as_view(), name='dashboard'),
    path('article_create/<str:user>', views.article_create.ArticleCreateView.as_view(), name='article_create'),
    path('articles/<str:user>', views.article_list.ArticleListView.as_view(), name='articles'),
    path('article/<str:username>/<int:pk>', views.article.ArticleView.as_view(), name='article'),
    path('signup/', views.signup.SignUpView.as_view(), name='signup'),
    path('likes/<int:user_id>/<int:article_id>', views.defs.likes, name='likes'),
    path('trainers/<str:user>', views.trainer_list.TrainersView.as_view(), name='trainers'),
    path('follow/<int:user_id>/<int:trainer_id>', views.defs.follow, name='follow'),
    path('trainer_detail/<str:slug>', views.trainer.TrainerView.as_view(), name='trainer_detail'),
]

bells_pro/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bells/', include('bells.urls')),
    path('bells/', include('django.contrib.auth.urls')),
    path('mdeditor/', include('mdeditor.urls'))
]


# markeditor用
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bells_pro/bells/models.py
from django.db import models
from mdeditor.fields import MDTextField

from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, Group, Permission, GroupManager, PermissionManager, ContentType
from django.utils import timezone
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _

from mediumeditor.widgets import MediumEditorTextarea
#　原本
class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.
    Username and password are required. Other fields are optional.
    """
    email = models.EmailField('email', unique=True)

    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        'username',
        max_length=150,
        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
        validators=[username_validator],
        error_messages={
            'unique': "A user with that username already exists.",
        },
    )
    is_staff = models.BooleanField(
        'staff status',
        default=False,
        help_text='Designates whether the user can log into this admin site.',
    )
    is_active = models.BooleanField(
        'is_active',
        default=True,
        help_text=
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ,
    )

    is_trainer=models.BooleanField(
        'is_trainer',
        default=False,
        help_text=
            'can write article',
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    follows = models.ManyToManyField(
        'self',
        symmetrical=False,
        related_name="followers",
        blank=True,
    )



    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)


    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


    def __str__(self):
        return self.username

    def natural_key(self):
        return (self.username,)

class Article(models.Model):
    title = models.CharField(max_length=70)
    detail = MDTextField()
    # detail = models.TextField()
    # detail = MediumEditorTextarea()
    trainer = models.ForeignKey(User, on_delete=models.CASCADE)

    user_likes = models.ManyToManyField(
        User,
        related_name="likes",
        blank=True,
    )

    user_favorites = models.ManyToManyField(
        User,
        related_name="favorites",
        blank=True,
    )
    def __str__(self):
        return self.title

class Comment(models.Model):
    comment = models.CharField(max_length=256)
    article = models.ForeignKey(
        Article, 
        related_name="comments",
        on_delete=models.CASCADE,
        )
    user = models.ForeignKey(
        User, 
        related_name="commets",
        on_delete=models.SET_NULL, 
        null = True
        )

class Tag(models.Model):
    tag = models.CharField(max_length=20)
    article = models.ManyToManyField(
        Article,
        related_name="tags",
        blank=True,
    )

class QuestionBox(models.Model):
    detail = models.TextField()
    user = models.ForeignKey(
        User,
        related_name="question_box",
        on_delete=models.CASCADE
    )

class Answer(models.Model):
    question_box = models.ForeignKey(
        QuestionBox,
        related_name = "answers",
        on_delete=models.CASCADE
    )
    User = models.ForeignKey(
        User,
        related_name="answers",
        on_delete=models.SET_NULL,
        null=True
    )

bells_pro/bells/views.py
# from django.urls import reverse_lazy
# from django.contrib.auth.decorators import login_required

# from django.http import HttpResponse
# from django.shortcuts import redirect
# from django.shortcuts import render
# from django.urls import reverse

# from django.views import generic
# from .form import UserCreateForm, UserLoginForm, ArticleForm, MyForm
# from django.contrib.auth import (
#      get_user_model, logout as auth_logout,
# )
# from django.contrib.auth.views import LoginView
# from .models.article import Article

# from django.contrib.auth.mixins import LoginRequiredMixin
# import datetime


# User = get_user_model()

# def index(request):
#     return render(request, 'bells/index.html')
 

# def likes(request, user_id, article_id):
#     """いいねボタンをクリック"""
#     if request.method == 'POST':
#         user = User.objects.get(id = user_id)
#         print(user.username)
#         article = Article.objects.get(id = article_id)
#         like_check = User.objects.filter(likes=article).filter(id=user_id)
#         if like_check.count() == 0:
#             user.likes.add(article)
#             user.save()
#         else:
#             user.likes.remove(article)
#             user.save()
        
#         context = {
#             'like_number': like_check.count()
#         }

#         # necessary return?
#         return HttpResponse("ajax is done!")


# class SignUpView(generic.CreateView):
#     form_class = UserCreateForm
#     success_url = reverse_lazy('login')
#     template_name = 'registration/signup.html'


# class ArticleCreateView(generic.CreateView, LoginRequiredMixin):
#     # markdown
#     form_class = ArticleForm
#     # MediumEditorの場合
#     # form_class = MyForm
#     template_name = 'dashboard/article_create.html'

#     def post(self, request, *args, **kwargs):
#         form = self.form_class(request.POST)
#         if form.is_valid():
#             obj = form.save(commit=False)
#             obj.trainer = self.request.user
#             obj.save()
            
#             return redirect('bells:articles', user=self.request.user)


# class UserLoginView(LoginView):
#     form_class = UserLoginForm
#     template_name = 'registration/login.html'

#     swappable = 'AUTH_USER_MODEL'

# class DashBoardView(generic.TemplateView, LoginRequiredMixin):
#     template_name='dashboard/dashboard.html'

#     def get_context_data(self, **kwargs):
#         today = datetime.datetime.now()
#         last_week = today - datetime.timedelta(weeks=2)
        
#         articles = Article.objects.all().order_by('created_at').reverse()[0:3]
#         pickups = Article.objects.filter(created_at__gt=last_week, created_at__lt=today).order_by('user_likes').reverse()[0:3]
#         context = super().get_context_data(**kwargs)
#         context['articles'] = articles
#         context['pickups'] = pickups

#         context['user'] = self.request.user
#         context['username'] = self.request.user.username
#         context['likes_count'] =  self.request.user.likes.count()

#         return context



# class ArticlesView(generic.TemplateView, LoginRequiredMixin):
#     articles = Article.objects.all()
#     template_name='dashboard/articles.html'
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['articles'] = Article.objects.all().order_by('created_at').reverse()
#         return context

# class ArticleView(generic.DetailView, LoginRequiredMixin):
#     model = Article
#     template_name = 'dashboard/article_detail.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         login_user = self.request.user
#         print(login_user.id)
#         context['articles'] = Article.objects.get(id=self.kwargs['pk'])
#         context['likes_number'] =  context['articles'].user_likes.count()

#         like_check = User.objects.filter(likes=context['articles']).filter(id=login_user.id).count()
#         context['like_check'] = False if like_check == 0 else True
#         context['login_user'] = login_user


#         return context

bells_pro/bells/views/article.py
from django.views import generic
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin

from ..models.article import Article

User = get_user_model()

class ArticleView(generic.DetailView, LoginRequiredMixin):
    model = Article
    template_name = 'dashboard/article_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        login_user = self.request.user
        context['articles'] = Article.objects.get(id=self.kwargs['pk'])
        context['likes_number'] =  context['articles'].user_likes.count()

        like_check = User.objects.filter(likes=context['articles']).filter(id=login_user.id).count()
        context['like_check'] = False if like_check == 0 else True
        context['login_user'] = login_user


        return context

bells_pro/bells/views/article_create.py
from django.views import generic
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin

from ..form import ArticleForm, MyForm


class ArticleCreateView(generic.CreateView, LoginRequiredMixin):
    # markdown
    form_class = ArticleForm
    # MediumEditorの場合
    # form_class = MyForm
    template_name = 'dashboard/article_create.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.trainer = self.request.user
            obj.save()
            
            return redirect('bells:articles', user=self.request.user)

bells_pro/bells/views/article_list.py
from django.views import generic
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from ..models.article import Article


class ArticleListView(generic.TemplateView, LoginRequiredMixin):
    articles = Article.objects.all()
    template_name='dashboard/articles.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles'] = Article.objects.all().order_by('created_at').reverse()
        return context

bells_pro/bells/views/dashboard.py
from django.views import generic
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from ..models.article import Article
import datetime

class DashBoardView(generic.TemplateView, LoginRequiredMixin):
    template_name='dashboard/dashboard.html'

    def get_context_data(self, **kwargs):
        today = datetime.datetime.now()
        last_week = today - datetime.timedelta(weeks=2)
        
        articles = Article.objects.all().order_by('created_at').reverse()[0:3]
        pickups = Article.objects.filter(created_at__gt=last_week, created_at__lt=today).order_by('user_likes').reverse()[0:3]
        context = super().get_context_data(**kwargs)
        context['articles'] = articles
        context['pickups'] = pickups

        context['user'] = self.request.user
        context['username'] = self.request.user.username
        context['likes_count'] =  self.request.user.likes.count()

        return context

bells_pro/bells/views/defs.py
from django.http import HttpResponse
from django.shortcuts import render
from ..models import User

def index(request):
    return render(request, 'bells/index.html')
 

def likes(request, user_id, article_id):
    """いいねボタンをクリック"""
    if request.method == 'POST':
        user = User.objects.get(id = user_id)
        article = Article.objects.get(id = article_id)
        like_check = User.objects.filter(likes=article).filter(id=user_id)
        if like_check.count() == 0:
            user.likes.add(article)
            user.save()
        else:
            user.likes.remove(article)
            user.save()
        
        context = {
            'like_number': like_check.count()
        }

        # necessary return?
        return HttpResponse("ajax is done!")

def follow(request, user_id, trainer_id):
    # followボタンをクリック
    if request.method == 'POST':
        user = User.objects.get(id = user_id)
        trainer = User.objects.get(id=trainer_id)
        # トレーナーのフォロワーの中に自分がいるかをチェック
        follow_check = trainer.followers.filter(id=user_id)

        if follow_check.count() == 0:
            user.follows.add(trainer)
            user.save()
        else:
            user.follows.remove(trainer)
            user.save()
        
        context = {
            'follow_number' : follow_check.count()
        }

        return HttpResponse("ajax is done!")    

bells_pro/bells/views/signup.py
from django.views import generic
from django.urls import reverse_lazy
from ..form import UserCreateForm



class SignUpView(generic.CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

bells_pro/bells/views/trainer.py
from django.views import generic
from django.urls import reverse

from ..models.user import User

class TrainerView(generic.DetailView):
    model = User
    template_name = "dashboard/trainer_detail.html"
    slug_field = 'username'

    def get_context_data(self, **kwargs):
        print(self.kwargs['slug'])

        context = super().get_context_data(**kwargs)
        context['trainer'] = User.objects.get(username=self.kwargs['slug'])
        # context['follower'] = context['trainer'][0].followers.count()
        # context['articles'] = context['follower'].trainer_set

        return context

bells_pro/bells/views/trainer_list.py
from django.views import generic
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from ..models.user import User


class TrainersView(generic.TemplateView, LoginRequiredMixin):
    template_name='dashboard/trainers.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trainers'] = User.objects.all().filter(is_trainer=True)
        context['user'] = self.request.user

        return context

bells_pro/bells/views/user_login.py
from django.contrib.auth.views import LoginView
from ..form import UserLoginForm

class UserLoginView(LoginView):
    form_class = UserLoginForm
    template_name = 'registration/login.html'

    swappable = 'AUTH_USER_MODEL'

bells_pro/bells/templates/dashboard/article_create.html
{% extends 'base_dashboard.html' %}

{% load bootstrap4 %}
{% load static %}

{% block dashboard %}
<div class="content">
    <form method="post" >
        {{user}}
        {{ form.title }}

        {{ form.id}}
        {% csrf_token %}
        {{ form.media }}
        {{ form.detail }}
        <p><input type="submit" value=送信></p>
    </form>

</div>


{% endblock %}

bells_pro/bells/templates/dashboard/article_detail.html
{% extends 'base_dashboard.html' %}

{% load bootstrap4 %}
{% load static %}
{% load markdown_extras %}

{% block dashboard %}
<div class="content">
    {{ article.title }}
    {{ article.likes}}
    {{ article.detail|markdown|safe }}
    <p>ログインユーザーがライクしているか:{{ like_check }}</p>
    <p>ライクされている数：{{ likes_number }}</p>
    <p>ログインユーザー {{ login_user }}</p>
    <p>所有者{{ article.trainer}}</p>
    {{user.id}}<br>
    {{article.created_at}}
    <ul>
        {% if like_check %}
            <li><a role="button" aria-pressed="true" onclick="likes(event, '{{ user.id }}','{{ article.id }}')">いいね！<span>({{ likes_number }})</span></a></li>
        {% else %}
            <li><a role="button" aria-pressed="false" onclick="likes(event, '{{ user.id }}','{{ article.id }}')">いいね！<span>({{ likes_number }})</span></a></li>
        {% endif %}
    </ul>
</div>


{% endblock %}

bells_pro/bells/templates/dashboard/articles.html
{% extends 'base_dashboard.html' %}

{% load bootstrap4 %}
{% load static %}
{% load markdown_extras %}

{% block dashboard %}
<div class="content">

    <ul>

        {% for article in articles%}
        <a href="{%  url 'bells:article' article.trainer article.id%}">
            <h2>{{article.title}}</h2>
            <li>{{ article.detail|markdown|safe }}</li>
        </a>
        <p>---------------</p>

        {% endfor %}
    </ul>
</div>


{% endblock %}

bells_pro/bells/templates/dashboard/dashboard.html
{% extends 'base_dashboard.html' %}

{% load bootstrap4 %}
{% load static %}
{% load markdown_extras %}
{% block dashboard %}
<div class="content">
    <!-- ここからuser -->
    <div class="row">
        <!-- 左半分、最新記事部 -->
        <div class="col-md-6">
        <h2>最新記事一覧</h2>
        {% for article in articles %}
          <div class="card card-user balance">
            <div class="card-header">
              <h5 class="card-title">{{ article.title }}</h5>
            </div>
            <div class="card-body">
              {{ article.detail|markdown|safe }}
              {{article.user_likes.count}}
            </div>
          </div>
          {% endfor %}
        </div>
        <!-- 右半分今週のピックアップ -->
        <div class="col-md-6">
            <h2>今週のピックアップ</h2>
            {%  for pickup in pickups %}
                <div class="card card-user balance">
                    <div class="card-header">
                      <h5 class="card-title">{{ pickup.title }}</h5>
                    </div>
                    <div class="card-body">
                    {{ pickup.detail|markdown|safe }}
                    <p>イイネ数:{{pickup.user_likes.count}}</p>
                    </div>
                </div>
            {% endfor %}

        </div>
      </div>

    {{username}}
    
    <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="{% url 'bells:article_create' user %}">記事作成へ</a>
    <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="{% url 'bells:articles' user %}">記事一覧へ</a>
</div>


{% endblock %}

bells_pro/bells/templates/dashboard/trainer_detail.html
{% extends 'base_dashboard.html' %}

{% load bootstrap4 %}
{% load static %}

{% block dashboard %}
<div class="content">
    {{ trainer.username }}
    {{ follower }}


</div>


{% endblock %}

bells_pro/bells/templates/dashboard/trainers.html
{% extends 'base_dashboard.html' %}

{% load bootstrap4 %}
{% load static %}
{% load follower_count %}
{% load follow_check %}

{% block dashboard %}
<div class="content">
    <ul>
        {% for trainer in trainers %}
            <div class="card card-user balance">
                <div class="card-header">
                    <a href="{% url 'bells:trainer_detail' trainer.username %}"><h2>{{　trainer.username }}</h2></a>
                </div>
                <div class="card-body">
                    <p>{{ trainer.id }}</p>
                    <p>フォロワー数:{% follower_count user.id trainer.id %}</p>
                    <p>フォロワー数:{{ trainer.followers.count }}</p>

                    <ul>
                        {% if trainer|follow_check:user.id %}
                            <li><a role="button" aria-pressed="true" onclick="follow(event, '{{ user.id }}','{{ trainer.id }}')">フォロー！<span>({%  follower_count user.id 　trainer.id %})</span></a></li>
                        {% else %}
                            <li><a role="button" aria-pressed="false" onclick="follow(event, '{{ user.id }}','{{ trainer.id }}')">フォロー！<span>({%  follower_count user.id 　trainer.id %})</span></a></li>
                        {% endif %}
                    </ul>
                </div>

            </div>

        {% endfor %}
    </ul>
</div>


{% endblock %}